In [ ]:
import numpy as np

## Question 1: Matrix Multiplication
Given matrices A and B:


A =[3,-2],[4,1]

B =[-1,3],[2,0]

Calculate the product AB.

In [66]:
matrixA = np.matrix([[3, -2], [4, 1]])
matrixB = np.matrix([[-1, 3], [2, 0]])

result = np.dot(matrixA, matrixB)
result

matrix([[-7,  9],
        [-2, 12]])

## Question 2: Inverse Matrix
Let matrix D be:

D =[4,2],[5,3]

Find the inverse of matrix D.

In [67]:
matrixD = np.matrix([[4, 2], [5, 3]])

result = np.linalg.inv(matrixD)
result

matrix([[ 1.5, -1. ],
        [-2.5,  2. ]])

## Question 3: Determinant

C =[-2,5],[3,1]

Compute the determinant of the matrix C.

In [68]:
matrixC = np.matrix([[-2, 5], [3, 1]])

result = np.linalg.det(matrixC)
result

-17.0

## Question 4: Transpose Matrix
Given matrix E:

E =[1,-3,2],[0,7,-1]

Find the transpose of matrix E^T.

In [69]:
matrixE = np.matrix([[1, -3, 2], [0, 7, -1]])
result = matrixE.transpose()
result

matrix([[ 1,  0],
        [-3,  7],
        [ 2, -1]])

## Question 5: Matrix Transformation
Perform the following matrix transformation on vector v:

v =[-1],[3]
   
using the transformation matrix:

T =[-2,1],[1,3]

In [70]:
matrixV = np.matrix([[-1], [3]])
matrixT = np.matrix([[-2, 1], [1, 3]])

result = matrixT @ matrixV
result

matrix([[5],
        [8]])

## Question 6: Change of Basis
Given a vector v in standard basis representation:

v =[2],[4]

Find the representation of v in a new basis B:

B =[3,1],[-2,5]

In [71]:
vectorV = np.array([[2], [4]])
B = np.array([[3, 1], [-2, 5]])

B_inv = np.linalg.inv(B)
v_in_B = B_inv @ vectorV

v_in_B

array([[0.35294118],
       [0.94117647]])

## Question 7: Eigenvalues and Eigenvectors
Given matrix F:

F=[5,-2],[-1,4]

Find the eigenvalues and eigenvectors of matrix F.

In [72]:
matrixF=np.matrix([[5,-2],[-1,4]])

values=np.linalg.eig(matrixF)
values

EigResult(eigenvalues=array([6., 3.]), eigenvectors=matrix([[ 0.89442719,  0.70710678],
        [-0.4472136 ,  0.70710678]]))

## Question 8: Conditional Probability
Given two events A and B with

P(A) = 0.7, P(B) = 0.5,

P(A ∩ B) = 0.3,

calculate the conditional probability P(A|B).

### Solution:

P(A∣B)= P(A∩B)/P(B)

In [ ]:
ProbA=0.7
ProbB=0.5
ProbIntersectionAB=0.3

result=ProbIntersectionAB/ProbB